import * as FaIcons from 'react-icons/fa';

const FaIconList = {
  user: <FaIcons.FaUser />,
  users: <FaIcons.FaUsers />,
  company: <FaIcons.FaBuilding />,
  phone: <FaIcons.FaPhone />,
  email: <FaIcons.FaEnvelope />,
  flag: <FaIcons.FaFlag />,
  photo: <FaIcons.FaCamera />,
  wrench: <FaIcons.FaWrench />,
  link: <FaIcons.FaLink />,
  github: <FaIcons.FaGithub />,
  twitter: <FaIcons.FaTwitter />,
  linkedin: <FaIcons.FaLinkedin />,
  folder: <FaIcons.FaFolder />,
  bolt: <FaIcons.FaBolt />,
  university: <FaIcons.FaUniversity />,
  globe: <FaIcons.FaGlobe />,
  code: <FaIcons.FaCode />,
  art: <FaIcons.FaPaintBrush />,
  video: <FaIcons.FaVideo />,
  rocket: <FaIcons.FaRocket />,
  legal: <FaIcons.FaGavel />,
  file: <FaIcons.FaFileAlt />,
  creditcard: <FaIcons.FaCreditCard />,
  facebook: <FaIcons.FaFacebook />,
  instagram: <FaIcons.FaInstagram />,
  youtube: <FaIcons.FaYoutube />,
  medium: <FaIcons.FaMedium />,
  reddit: <FaIcons.FaReddit />,
  question: <FaIcons.FaQuestion />,
};

export default FaIconList;
