// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: external.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const findObjectByAliasOrIDString = `-- name: FindObjectByAliasOrIDString :one
SELECT o.id, o.name, o.photo, o.description, o.id_string, o.creator_id, o.created_at, o.deleted_at, o.aliases FROM obj o
JOIN creator c ON o.creator_id = c.id
WHERE c.org_id = $3 
AND o.deleted_at IS NULL
AND (o.id_string = $1 OR $2 = ANY(o.aliases))
`

type FindObjectByAliasOrIDStringParams struct {
	IDString string    `json:"id_string"`
	Aliases  []string  `json:"aliases"`
	OrgID    uuid.UUID `json:"org_id"`
}

func (q *Queries) FindObjectByAliasOrIDString(ctx context.Context, arg FindObjectByAliasOrIDStringParams) (Obj, error) {
	row := q.queryRow(ctx, q.findObjectByAliasOrIDStringStmt, findObjectByAliasOrIDString, arg.IDString, pq.Array(arg.Aliases), arg.OrgID)
	var i Obj
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Photo,
		&i.Description,
		&i.IDString,
		&i.CreatorID,
		&i.CreatedAt,
		&i.DeletedAt,
		pq.Array(&i.Aliases),
	)
	return i, err
}
