// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stats.sql

package database

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
Select 1
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.healthCheckStmt, healthCheck)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
